"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {Button,Input} from "@/components/ui";
export default function Onboarding(){
 const router=useRouter(),[step,setStep]=useState("loading"),[username,setUsername]=useState(""),[displayName,setDisplayName]=useState(""),[address,setAddress]=useState(""),[accepted,setAccepted]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/onboarding");const j=await r.json();if(!j.data?.authenticated){router.replace("/auth/verify");return}setStep(j.data.step);setAddress(j.data.address?.address||"");setDisplayName(j.data.profile?.display_name||"");}
 useEffect(()=>{load()},[]);
 async function next(payload:any){setBusy(true);setError("");const r=await fetch("/api/onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();setBusy(false);if(!j.success){setError(j.error?.message||"Something went wrong. Try again.");return}if(payload.step==="address"){setAddress(j.data.address.address);setStep("profile")}else if(payload.step==="profile")setStep("tos");else if(payload.step==="tos")setStep("complete");else router.replace("/mail")}
 if(step==="loading")return <main className="min-h-screen bg-zinc-50"/>;
 return <main className="flex min-h-screen items-center justify-center bg-zinc-50 p-6"><section className="w-full max-w-xl rounded-3xl bg-white p-8 shadow-sm"><div className="text-sm font-black">coldmail</div><div className="mt-8 flex gap-2">{["address","profile","tos"].map(x=><div key={x} className={"h-1 flex-1 rounded-full "+(["profile","tos","complete"].includes(step)&&x==="address"||["tos","complete"].includes(step)&&x==="profile"||step==="complete"&&x==="tos"||step===x?"bg-black":"bg-zinc-200")}/>)}</div>{step==="address"&&<><h1 className="mt-8 text-4xl font-black">Choose your Coldmail address</h1><p className="mt-3 text-zinc-500">This is the address people will use to send you mail.</p><div className="mt-8 flex items-center gap-2"><Input value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="yourname"/><span className="font-semibold">@coldmail.com</span></div><Button className="mt-5 w-full" disabled={busy} onClick={()=>next({step:"address",username,displayName:username})}>{busy?"Checking…":"Continue"}</Button></>}{step==="profile"&&<><h1 className="mt-8 text-4xl font-black">Set up your profile</h1><p className="mt-3 text-zinc-500">Choose the name shown on your mail.</p><Input className="mt-8" value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Display name"/><p className="mt-3 text-sm text-zinc-500">Your address: <b>{address}</b></p><Button className="mt-5 w-full" disabled={busy} onClick={()=>next({step:"profile",displayName})}>{busy?"Saving…":"Continue"}</Button></>}{step==="tos"&&<><h1 className="mt-8 text-4xl font-black">One last step</h1><p className="mt-3 text-zinc-500">Review and accept the Coldmail Terms of Service before using your mailbox.</p><label className="mt-8 flex gap-3 rounded-2xl border p-4 text-sm"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I agree to the Coldmail Terms of Service, version 1.0.</span></label><Button className="mt-5 w-full" disabled={!accepted||busy} onClick={()=>next({step:"tos",accepted})}>{busy?"Saving…":"Accept and continue"}</Button></>}{step==="complete"&&<><h1 className="mt-8 text-4xl font-black">You're in.</h1><p className="mt-3 text-zinc-500">Your account, address, profile, folders, and legal acceptance are saved.</p><Button className="mt-8 w-full" onClick={()=>next({step:"complete"})}>Open Coldmail</Button></>}{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</section></main>;
}