"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {Button,Input,Textarea} from "@/components/ui";
export default function Mail(){
 const [folder,setFolder]=useState("inbox"),[rows,setRows]=useState<any[]>([]),[open,setOpen]=useState<any>(null),[to,setTo]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[q,setQ]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const o=await fetch("/api/onboarding");const oj=await o.json();if(oj.data?.authenticated&&oj.data.step!=="complete"){location.href="/onboarding";return}const r=await fetch("/api/mailbox?folder="+encodeURIComponent(folder)+(q?"&q="+encodeURIComponent(q):""));const j=await r.json();setRows(j.data||[])}
 useEffect(()=>{load()},[folder]);
 async function send(){setBusy(true);const r=await fetch("/api/mail/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({to:to.split(",").map(x=>x.trim()).filter(Boolean),subject,body})});const j=await r.json();setBusy(false);if(!j.success){alert(j.error?.message||"Send failed");return}setTo("");setSubject("");setBody("");await load()}
 async function update(id:string,p:any){await fetch("/api/mailbox",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...p})});await load()}
 return <main className="min-h-screen bg-zinc-50 text-zinc-950"><header className="border-b bg-white px-5 py-4 flex items-center justify-between"><div><div className="text-xl font-black">coldmail</div><div className="text-xs text-zinc-500">IMPF mail</div></div><div className="flex gap-3"><Link href="/settings" className="text-sm">Settings</Link></div></header><div className="mx-auto grid max-w-7xl gap-4 p-4 lg:grid-cols-[180px_1fr_380px]"><aside className="rounded-2xl bg-white p-3">{["inbox","sent","drafts","archive","spam","trash"].map(x=><button key={x} onClick={()=>setFolder(x)} className={"w-full rounded-xl px-3 py-2 text-left text-sm "+(folder===x?"bg-black text-white":"hover:bg-zinc-100")}>{x}</button>)}</aside><section className="rounded-2xl bg-white overflow-hidden"><div className="border-b p-4 flex gap-2"><Input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search mail"/><Button onClick={load}>Search</Button></div>{rows.map(r=><div key={r.id} className="border-b p-4 hover:bg-zinc-50"><button className="w-full text-left" onClick={()=>{setOpen(r);if(!r.is_read)update(r.id,{is_read:true})}}><div className="flex justify-between"><span className={r.is_read?"":"font-bold"}>{r.messages?.subject||"(no subject)"}</span><span className="text-xs text-zinc-400">{new Date(r.created_at).toLocaleString()}</span></div><div className="truncate text-sm text-zinc-500">{r.messages?.body||""}</div></button><div className="mt-2 flex gap-2"><button className="text-xs" onClick={()=>update(r.id,{is_starred:!r.is_starred})}>{r.is_starred?"★":"☆"}</button><button className="text-xs" onClick={()=>update(r.id,{folder:"archive"})}>Archive</button><button className="text-xs" onClick={()=>update(r.id,{folder:"trash"})}>Delete</button></div></div>)}{!rows.length&&<div className="p-10 text-center text-zinc-500">No mail here.</div>}</section><section className="rounded-2xl bg-white p-5"><h2 className="mb-3 font-bold">Compose</h2><Input value={to} onChange={e=>setTo(e.target.value)} placeholder="To: user@coldmail.com"/><Input className="mt-2" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><Textarea className="mt-2 min-h-48" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write your message…"/><Button className="mt-3 w-full" disabled={busy} onClick={send}>{busy?"Sending…":"Send with IMPF"}</Button>{open&&<div className="mt-6 border-t pt-4"><div className="font-bold">{open.messages?.subject}</div><p className="mt-3 whitespace-pre-wrap text-sm">{open.messages?.body}</p></div>}</section></div></main>
}